# This file contains the parameters for the global planner used in the move_base node.
GlobalPlanner:
  allow_unknown: true # defualt false
  default_tolerance: 0.2
  visualize_potential: false
  use_dijkstra: true
  use_quadratic: true
  use_grid_path: false # default true
  old_navfn_behavior: false

  lethal_cost: 253 
  neutral_cost: 50 # 72
  cost_factor: 0.48 # 0.48
  publish_potential: true
  orientation_mode: 0
  orientation_window_size: 1